/**
 * The catalogue, transcribed from the shop posters.
 * All money is in cents (R45.00 === 4500).
 */

export const categories = [
  {
    slug: 'wings',
    name: 'Wings',
    icon: '🍗',
    blurb: 'Crispy. Juicy. Irresistible.',
    items: [
      {
        slug: 'dunked-wings',
        name: 'Dunked Wings',
        description:
          'Wings tossed in rich, bold sauces for that explosive flavour. Choose your portion and heat.',
        basePrice: 2500,
        badge: 'Best seller',
        prepMinutes: 18,
        groups: [
          {
            name: 'Portion',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Small (6 wings)', delta: 0 },
              { name: 'Medium (10 wings)', delta: 1000 },
              { name: 'Large (15 wings)', delta: 2000 },
            ],
          },
          {
            name: 'Sauce',
            kind: 'multi',
            required: true,
            maxPick: 2,
            options: [
              { name: 'BBQ', delta: 0 },
              { name: 'Hot', delta: 0 },
              { name: 'Peri-Peri', delta: 0 },
              { name: 'Honey Garlic', delta: 0 },
            ],
          },
          {
            name: 'Add-ons',
            kind: 'multi',
            required: false,
            maxPick: 3,
            options: [
              { name: 'Extra dipping sauce', delta: 500 },
              { name: 'Cheesy fries', delta: 2500 },
              { name: 'Side salad', delta: 1800 },
            ],
          },
        ],
      },
      {
        slug: 'normale-wings',
        name: 'Normale Wings',
        description: 'Perfectly seasoned, crispy on the outside, juicy on the inside.',
        basePrice: 2500,
        prepMinutes: 16,
        groups: [
          {
            name: 'Portion',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Small (6 wings)', delta: 0 },
              { name: 'Medium (10 wings)', delta: 1000 },
              { name: 'Large (15 wings)', delta: 2000 },
            ],
          },
          {
            name: 'Dust it',
            kind: 'multi',
            required: false,
            maxPick: 2,
            options: [
              { name: 'Peri-peri sprinkle', delta: 0 },
              { name: 'Lemon pepper', delta: 300 },
              { name: 'Smoky BBQ rub', delta: 300 },
            ],
          },
        ],
      },
      {
        slug: 'wings-sauce-flight',
        name: 'Sauce Flight',
        description: 'All four house sauces in little cups, for the table that cannot decide.',
        basePrice: 2500,
        prepMinutes: 5,
        groups: [],
      },
    ],
  },
  {
    slug: 'sandwiches',
    name: 'Sandwiches & Chips',
    icon: '🥪',
    blurb: 'Toasted, golden, made to order.',
    items: [
      {
        slug: 'toasted-sandwich',
        name: 'Toasted Sandwich',
        description: 'Crispy on the outside, warm & cheesy on the inside.',
        basePrice: 4500,
        badge: 'Lunch favourite',
        prepMinutes: 10,
        groups: [
          {
            name: 'Filling',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Cheese & tomato', delta: 0 },
              { name: 'Chicken mayo', delta: 1500 },
              { name: 'Ham & cheese', delta: 1800 },
              { name: 'Russian & cheese', delta: 2500 },
            ],
          },
          {
            name: 'Make it a meal',
            kind: 'single',
            required: false,
            maxPick: 1,
            options: [
              { name: 'Sandwich only', delta: 0 },
              { name: '+ chips & cold drink', delta: 2500 },
            ],
          },
        ],
      },
      {
        slug: 'chips',
        name: 'Chips',
        description: 'Golden, crispy & perfectly seasoned. Fryer fresh.',
        basePrice: 2500,
        prepMinutes: 8,
        groups: [
          {
            name: 'Size',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Regular', delta: 0 },
              { name: 'Large', delta: 1000 },
            ],
          },
          {
            name: 'Toppings',
            kind: 'multi',
            required: false,
            maxPick: 3,
            options: [
              { name: 'Cheese sauce', delta: 500 },
              { name: 'Russian', delta: 1500 },
              { name: 'BBQ spice', delta: 300 },
              { name: 'Peri-peri salt', delta: 300 },
            ],
          },
        ],
      },
      {
        slug: 'russian-roll',
        name: 'Russian & Chips Combo',
        description: 'Grilled russian, tangy chakalaka, hand-cut chips.',
        basePrice: 5500,
        prepMinutes: 15,
        groups: [],
      },
    ],
  },
  {
    slug: 'platters',
    name: 'Platters',
    icon: '🍽️',
    blurb: 'Perfect for any occasion — made to share.',
    items: [
      {
        slug: 'ultimate-sharing-platter',
        name: 'The Ultimate Sharing Platter',
        description: 'The ultimate sharing experience: wings, ribs, chips, dips and sides for the whole table.',
        basePrice: 75000,
        badge: 'Feeds 6–8',
        prepMinutes: 40,
        trackStock: true,
        stock: 6,
        groups: [
          {
            name: 'Wing sauce',
            kind: 'multi',
            required: true,
            maxPick: 2,
            options: [
              { name: 'BBQ', delta: 0 },
              { name: 'Hot', delta: 0 },
              { name: 'Peri-Peri', delta: 0 },
              { name: 'Honey Garlic', delta: 0 },
            ],
          },
        ],
      },
      {
        slug: 'feast-to-share',
        name: 'A Feast to Share',
        description: 'A feast to share, a memory to keep — wings, wors, chips and salad.',
        basePrice: 65000,
        badge: 'Feeds 4–6',
        prepMinutes: 35,
        trackStock: true,
        stock: 8,
        groups: [],
      },
      {
        slug: 'fresh-flavourful-platter',
        name: 'Fresh & Flavourful Platter',
        description: 'Fresh, flavorful and perfectly shared — grilled chicken, veg and dips.',
        basePrice: 52000,
        badge: 'Feeds 3–4',
        prepMinutes: 30,
        trackStock: true,
        stock: 8,
        groups: [],
      },
    ],
  },
  {
    slug: 'desserts',
    name: 'Indulgent Desserts',
    icon: '🍨',
    blurb: 'Creamy custard, fresh berries, crunchy granola.',
    items: [
      {
        slug: 'dessert-delight',
        name: 'Indulgent Dessert Delight',
        description:
          'Layers of creamy custard, fresh berries and crunchy granola finished with a Lotus biscuit.',
        basePrice: 4999,
        badge: 'Perfect for any occasion',
        prepMinutes: 6,
        groups: [
          {
            name: 'Sauce',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Belgian chocolate', delta: 0 },
              { name: 'Strawberry coulis', delta: 0 },
              { name: 'Salted caramel', delta: 0 },
              { name: 'Oreo crumble', delta: 500 },
            ],
          },
          {
            name: 'Toppings',
            kind: 'multi',
            required: false,
            maxPick: 4,
            options: [
              { name: 'Fresh berries', delta: 800 },
              { name: 'Crushed biscuits', delta: 300 },
              { name: 'Extra cream', delta: 400 },
              { name: 'Granola crunch', delta: 400 },
            ],
          },
        ],
      },
      {
        slug: 'cake-slice',
        name: 'Cake Slice',
        description: 'A generous slice of the cake of the day — ask us what is on the stand.',
        basePrice: 3000,
        prepMinutes: 3,
        trackStock: true,
        stock: 18,
        groups: [],
      },
      {
        slug: 'ice-cream-sundae',
        name: 'Ice Cream Sundae',
        description: 'Soft serve, hot sauce, crushed nuts.',
        basePrice: 3500,
        prepMinutes: 5,
        groups: [
          {
            name: 'Flavour',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Vanilla', delta: 0 },
              { name: 'Chocolate', delta: 0 },
              { name: 'Strawberry', delta: 0 },
              { name: 'Swirl', delta: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    slug: 'sweet-treats',
    name: 'Sweet Treats & Bakery',
    icon: '🧁',
    blurb: 'Baked with passion, made with love.',
    items: [
      {
        slug: 'celebration-cake',
        name: 'Celebration Cake',
        description:
          'Made-to-order celebration cake with buttercream finish, fresh flowers and gold detail. 48 hours notice.',
        basePrice: 45000,
        badge: 'Order 48h ahead',
        prepMinutes: 60,
        trackStock: true,
        stock: 3,
        groups: [
          {
            name: 'Size',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: '20 cm (feeds 12)', delta: 0 },
              { name: '25 cm (feeds 20)', delta: 25000 },
              { name: '30 cm (feeds 35)', delta: 55000 },
            ],
          },
          {
            name: 'Sponge',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Vanilla', delta: 0 },
              { name: 'Chocolate', delta: 0 },
              { name: 'Red velvet', delta: 5000 },
              { name: 'Lemon', delta: 3000 },
            ],
          },
          {
            name: 'Message on the cake',
            kind: 'multi',
            required: false,
            maxPick: 4,
            options: [
              { name: 'Name in gold lettering', delta: 2000 },
              { name: 'Fresh flowers', delta: 5000 },
              { name: 'Edible glitter', delta: 2500 },
              { name: 'Cake topper', delta: 3500 },
            ],
          },
        ],
      },
      {
        slug: 'cupcake-box',
        name: 'Cupcake Box (6)',
        description: 'Six cupcakes with buttercream swirls, strawberries and a dusting of sparkle.',
        basePrice: 6000,
        prepMinutes: 10,
        trackStock: true,
        stock: 12,
        groups: [
          {
            name: 'Frosting',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Pink vanilla', delta: 0 },
              { name: 'Chocolate', delta: 0 },
              { name: 'Mixed box', delta: 500 },
            ],
          },
        ],
      },
      {
        slug: 'brownie-batch',
        name: 'Brownie Batch (9)',
        description: 'Fudgy chocolate brownies cut into nine squares, drizzled and sprinkled.',
        basePrice: 9000,
        badge: 'Fudgy',
        prepMinutes: 8,
        trackStock: true,
        stock: 10,
        groups: [],
      },
      {
        slug: 'koeksisters',
        name: 'Koeksisters (4)',
        description: 'Syrupy, plaited and best eaten over the sink.',
        basePrice: 3500,
        prepMinutes: 5,
        trackStock: true,
        stock: 24,
        groups: [],
      },
      {
        slug: 'crunchie-biscuits',
        name: 'Crunchie Biscuits (6)',
        description: 'Golden oat crunchies baked in the tray and cut thick.',
        basePrice: 4000,
        prepMinutes: 5,
        trackStock: true,
        stock: 20,
        groups: [],
      },
    ],
  },
  {
    slug: 'popcorn',
    name: 'Popcorn Bar',
    icon: '🍿',
    blurb: 'Popped to perfection — a perfect snack for every moment.',
    items: [
      {
        slug: 'classic-salted-popcorn',
        name: 'Classic Salted Popcorn',
        description: 'Hot, buttery and salted just right.',
        basePrice: 1500,
        prepMinutes: 4,
        groups: [popcornSize(), popcornAddOns()],
      },
      {
        slug: 'caramel-sweet-popcorn',
        name: 'Caramel Sweet Popcorn',
        description: 'Sticky caramel glaze, popped fresh daily.',
        basePrice: 2000,
        prepMinutes: 4,
        groups: [popcornSize(), popcornAddOns()],
      },
      {
        slug: 'butter-popcorn',
        name: 'Butter Popcorn',
        description: 'Cinema-style butter, extra generous.',
        basePrice: 1500,
        prepMinutes: 4,
        groups: [popcornSize(), popcornAddOns()],
      },
      {
        slug: 'chocolate-delight-popcorn',
        name: 'Chocolate Delight Popcorn',
        description: 'Dark chocolate drizzle over caramel popcorn.',
        basePrice: 2000,
        prepMinutes: 5,
        groups: [popcornSize(), popcornAddOns()],
      },
      {
        slug: 'cheese-burst-popcorn',
        name: 'Cheese Burst Popcorn',
        description: 'Sharp cheddar dusting, dangerously moreish.',
        basePrice: 2000,
        prepMinutes: 5,
        groups: [popcornSize(), popcornAddOns()],
      },
    ],
  },
  {
    slug: 'drinks',
    name: 'Drinks',
    icon: '🥤',
    blurb: 'Cheers to good times!',
    items: [
      {
        slug: 'strawberry-mocktail',
        name: 'Strawberry Mocktail',
        description: 'Muddled strawberries, lime, crushed ice and mint.',
        basePrice: 3500,
        prepMinutes: 6,
        groups: [],
      },
      {
        slug: 'mint-lime-cooler',
        name: 'Mint & Lime Cooler',
        description: 'Tall, icy and very refreshing. Served with a lime wheel.',
        basePrice: 3500,
        prepMinutes: 6,
        groups: [],
      },
      {
        slug: 'berry-blast',
        name: 'Berry Blast',
        description: 'Mixed berry cooler with a strawberry garnish.',
        basePrice: 4000,
        prepMinutes: 6,
        groups: [],
      },
      {
        slug: 'cold-drink-330ml',
        name: 'Cold Drink 330ml',
        description: 'Coke, Fanta, Sprite or Stoney — tell us which.',
        basePrice: 1500,
        prepMinutes: 1,
        groups: [
          {
            name: 'Flavour',
            kind: 'single',
            required: true,
            maxPick: 1,
            options: [
              { name: 'Coca-Cola', delta: 0 },
              { name: 'Fanta Orange', delta: 0 },
              { name: 'Sprite', delta: 0 },
              { name: 'Stoney', delta: 0 },
            ],
          },
        ],
      },
      {
        slug: 'water-500ml',
        name: 'Still Water 500ml',
        description: 'Chilled still water.',
        basePrice: 1000,
        prepMinutes: 1,
        groups: [],
      },
    ],
  },
];

function popcornSize() {
  return {
    name: 'Size',
    kind: 'single',
    required: true,
    maxPick: 1,
    options: [
      { name: 'Regular cup', delta: 0 },
      { name: 'Large cup', delta: 1000 },
      { name: 'Sharing tub', delta: 2500 },
    ],
  };
}

function popcornAddOns() {
  return {
    name: 'Add-ons',
    kind: 'multi',
    required: false,
    maxPick: 3,
    options: [
      { name: 'Extra cheese', delta: 500 },
      { name: 'Extra caramel', delta: 500 },
      { name: 'Chocolate drizzle', delta: 700 },
    ],
  };
}

export const promos = [
  {
    code: 'WINGS10',
    kind: 'percent',
    value: 10,
    minSubtotal: 15000,
    maxUses: 500,
    description: '10% off orders over R150 — wing night sorted.',
    expiresAt: null,
  },
  {
    code: 'TREAT50',
    kind: 'fixed',
    value: 5000,
    minSubtotal: 30000,
    maxUses: 200,
    description: 'R50 off a R300 basket for the sweet tooth.',
    expiresAt: null,
  },
  {
    code: 'FREERIDE',
    kind: 'free_delivery',
    value: 0,
    minSubtotal: 20000,
    maxUses: 300,
    description: 'Free delivery on orders over R200 within 12 km.',
    expiresAt: null,
  },
  {
    code: 'PLATTERDAY',
    kind: 'percent',
    value: 15,
    minSubtotal: 50000,
    maxUses: 100,
    description: '15% off any platter order over R500.',
    expiresAt: null,
  },
];

export const demoUsers = [
  {
    name: 'Khanyisile Mabuza',
    email: 'admin@demo.kk',
    phone: '082 837 3077',
    password: 'demo1234',
    role: 'admin',
  },
  {
    name: 'Nomsa Mokoena',
    email: 'customer@demo.kk',
    phone: '073 811 2207',
    password: 'demo1234',
    role: 'customer',
    loyalty: 240,
    addresses: [
      {
        label: 'Home',
        line1: '1123 Malamulele Main Road',
        suburb: 'Malamulele B',
        notes: 'Green gate next to the crèche, hoot twice.',
        lat: -22.9611,
        lng: 30.7195,
        isDefault: 1,
      },
      {
        label: 'Work',
        line1: 'Malamulele Plaza, Shop 14',
        suburb: 'Malamulele',
        notes: 'Ask for Nomsa at reception.',
        lat: -22.9542,
        lng: 30.7331,
        isDefault: 0,
      },
    ],
  },
  {
    name: 'Sipho Ndlovu',
    email: 'driver@demo.kk',
    phone: '072 445 8891',
    password: 'demo1234',
    role: 'driver',
    driver: { vehicle: 'scooter', plate: 'KZ 12 SB', zone: 'Malamulele', status: 'online', rating: 4.9, deliveries: 148 },
  },
  {
    name: 'Thabo Rikhotso',
    email: 'thabo.rider@demo.kk',
    phone: '076 220 4417',
    password: 'demo1234',
    role: 'driver',
    driver: { vehicle: 'bike', plate: '—', zone: 'Malamulele East', status: 'online', rating: 4.7, deliveries: 62 },
  },
  {
    name: 'Grace Mthembu',
    email: 'grace.rider@demo.kk',
    phone: '081 908 2233',
    password: 'demo1234',
    role: 'driver',
    driver: { vehicle: 'car', plate: 'JT 88 MN', zone: 'Malamulele West', status: 'offline', rating: 5.0, deliveries: 24 },
  },
  {
    name: 'Tinyiko Baloyi',
    email: 'tinyiko@demo.kk',
    phone: '071 336 5512',
    password: 'demo1234',
    role: 'customer',
    loyalty: 85,
    addresses: [
      {
        label: 'Home',
        line1: '88 Giyani Road',
        suburb: 'Malamulele A',
        notes: 'Blue roof, opposite the filling station.',
        lat: -22.9481,
        lng: 30.7412,
        isDefault: 1,
      },
    ],
  },
];
