import crypto from 'node:crypto';
import express from 'express';
import { get, all } from '../db/index.js';
import { ApiError, asyncHandler, created, send } from '../lib/http.js';
import v from '../lib/validate.js';
import { requireAuth } from '../middleware/auth.js';
import { rateLimitMiddleware } from '../lib/rateLimit.js';
import { priceCart, validatePromo } from '../services/pricing.js';
import { getTunables } from '../services/settings.js';
import {
  createOrder, transition, hydrate, getOrderById, getOrderByCode, assertCanView,
  listForUser, rateOrder,
} from '../services/orders.js';
import { refreshDriverStatus } from '../services/dispatch.js';

const router = express.Router();

const cartSchema = v.object({
  items: v
    .array(
      v.object({
        itemId: v.int({ min: 1 }),
        qty: v.int({ min: 1, max: 50 }).optional(),
        optionIds: v.array(v.int({ min: 1 }), { max: 20 }).optional(),
        notes: v.text({ max: 200 }).optional(),
      }),
      { min: 1, max: 40 },
    ),
  fulfilment: v.enum(['collection', 'delivery']).optional(),
  address: v
    .object({
      line1: v.string({ min: 4, max: 160 }),
      suburb: v.string({ max: 80 }).optional(),
      notes: v.text({ max: 240 }).optional(),
      lat: v.number({ min: -90, max: 90 }).optional(),
      lng: v.number({ min: -180, max: 180 }).optional(),
    })
    .optional(),
  promoCode: v.string({ max: 24 }).optional(),
  redeemPoints: v.int({ min: 0, max: 100000 }).optional(),
});

/**
 * Price a basket without committing to anything. The storefront calls this
 * on every change so the customer always sees the true total, delivery fee,
 * promo result and ETA — including “sold out”, “too far” and “minimum order”.
 */
router.post(
  '/quote',
  rateLimitMiddleware({ scope: 'quote', limit: 120, windowMs: 60 * 1000 }),
  asyncHandler((req, res) => {
    const body = cartSchema.parse(req.body);
    const quote = priceCart({
      items: body.items,
      fulfilment: body.fulfilment,
      address: body.address ?? null,
      promoCode: body.promoCode ?? '',
      redeemPoints: body.redeemPoints ?? 0,
      user: req.user ?? null,
    });
    return send(res, quote);
  }),
);

/** Validate a promo code on its own so the UI can give fast feedback. */
router.get(
  '/promo/:code',
  asyncHandler((req, res) => {
    const subtotal = Number(req.query.subtotal ?? 0);
    const result = validatePromo(req.params.code, Number.isFinite(subtotal) ? subtotal : 0);
    if (!result.ok) throw ApiError.unprocessable(result.message);
    return send(res, {
      promo: {
        code: result.code,
        kind: result.kind,
        value: result.value,
        minSubtotal: result.min_subtotal,
        description: result.description,
      },
    });
  }),
);

/**
 * Place an order.
 *
 * Two safety nets for a double-tapped "Place order" on a flaky connection:
 *   1. an Idempotency-Key header (generated by the client per basket), and
 *   2. a content hash of the basket as the fallback key.
 * Both paths return the original order rather than charging twice.
 */
router.post(
  '/',
  requireAuth,
  rateLimitMiddleware({ scope: 'order-create', limit: 12, windowMs: 5 * 60 * 1000, by: 'user' }),
  asyncHandler((req, res) => {
    const body = cartSchema.parse(req.body);
    const headerKey = req.get('idempotency-key');

    const fingerprint = headerKey
      ? `hdr:${headerKey.slice(0, 80)}`
      : `hash:${crypto
          .createHash('sha256')
          .update(
            JSON.stringify({
              u: req.user.id,
              items: body.items,
              f: body.fulfilment ?? 'collection',
              a: body.address?.line1 ?? '',
            }),
          )
          .digest('hex')
          .slice(0, 40)}`;

    // Same basket, placed twice within 3 minutes → replay the first order.
    const recent = get(
      `SELECT id, code FROM orders
        WHERE user_id = ? AND idempotency_key = ? AND created_at >= datetime('now','-3 minutes')`,
      [req.user.id, fingerprint],
    );
    if (recent) {
      return send(res, {
        order: hydrate(getOrderById(recent.id)),
        replayed: true,
        message: `You already placed ${recent.code} — here it is again.`,
      });
    }

    const { order } = createOrder({ user: req.user, payload: body, idempotencyKey: fingerprint });
    return created(res, { order, replayed: false });
  }),
);

/** A customer's own order history. */
router.get(
  '/',
  requireAuth,
  asyncHandler((req, res) => {
    const limit = Math.min(100, Math.max(1, Number(req.query.limit ?? 30)));
    const orders = listForUser(req.user.id, { limit });
    return send(res, {
      orders,
      active: orders.filter((o) => !['completed', 'cancelled', 'rejected', 'delivered'].includes(o.status)),
    });
  }),
);

/** Look up one order by id or by its KK-XXXXXX code. */
router.get(
  '/:idOrCode',
  requireAuth,
  asyncHandler((req, res) => {
    const raw = req.params.idOrCode;
    const order = /^\d+$/.test(raw) ? getOrderById(Number(raw)) : getOrderByCode(raw);
    assertCanView(order, req.user);
    return send(res, { order: hydrate(order) });
  }),
);

router.post(
  '/:id/cancel',
  requireAuth,
  asyncHandler((req, res) => {
    const body = v.object({ reason: v.text({ max: 240 }).optional() }).parse(req.body ?? {});
    const order = getOrderById(Number(req.params.id));
    assertCanView(order, req.user);

    const fresh = transition(order.id, 'cancelled', {
      actor: req.user,
      reason: body.reason ?? 'Cancelled by customer',
    });
    return send(res, { order: fresh });
  }),
);

/**
 * Push an order along the state machine (admin and driver consoles).
 * The service layer decides whether that move is legal for this role.
 */
router.post(
  '/:id/transition',
  requireAuth,
  asyncHandler((req, res) => {
    const body = v
      .object({
        to: v.enum([
          'confirmed', 'preparing', 'ready', 'assigned', 'picked_up',
          'on_the_way', 'delivered', 'completed', 'cancelled', 'rejected',
        ]),
        note: v.text({ max: 240 }).optional(),
        reason: v.text({ max: 240 }).optional(),
        driverId: v.int({ min: 1 }).optional(),
      })
      .parse(req.body);

    if (req.user.role === 'customer' && body.to !== 'cancelled' && body.to !== 'completed') {
      throw ApiError.forbidden('Customers can only cancel their own order');
    }

    const order = getOrderById(Number(req.params.id));
    if (!order) throw ApiError.notFound('Order not found');
    if (req.user.role === 'driver') {
      const driver = get('SELECT id FROM drivers WHERE user_id = ?', [req.user.id]);
      if (!driver || (order.driver_id !== driver.id && body.to !== 'assigned')) {
        throw ApiError.forbidden('That order is not assigned to you');
      }
    }

    const fresh = transition(order.id, body.to, {
      actor: req.user,
      note: body.note ?? '',
      reason: body.reason ?? '',
      driverId: body.driverId,
    });
    if (order.driver_id || fresh.driver_id) refreshDriverStatus(fresh.driver_id ?? order.driver_id);
    return send(res, { order: fresh });
  }),
);

/** Receipt re-print — the kitchen uses this for the paper ticket. */
router.get(
  '/:id/receipt',
  requireAuth,
  asyncHandler((req, res) => {
    const order = getOrderById(Number(req.params.id));
    assertCanView(order, req.user);
    const model = hydrate(order);
    return send(res, {
      receipt: {
        code: model.code,
        placedAt: model.created_at,
        fulfilment: model.fulfilment,
        status: model.status,
        customer: model.customer_name,
        phone: model.customer_phone,
        address: model.fulfilment === 'delivery'
          ? `${model.address_line}${model.address_suburb ? `, ${model.address_suburb}` : ''}`
          : 'Collection from the kitchen',
        lines: model.items.map((i) => ({
          name: i.name,
          qty: i.qty,
          unitPrice: i.unit_price,
          lineTotal: i.line_total,
          options: i.options.map((o) => o.name).join(', '),
        })),
        subtotal: model.subtotal,
        deliveryFee: model.delivery_fee,
        discount: model.discount,
        total: model.total,
        paymentMethod: model.payment_method,
        events: model.events.map((e) => ({ at: e.created_at, status: e.to_state, by: e.actor_name })),
      },
    });
  }),
);

router.post(
  '/:id/rate',
  requireAuth,
  asyncHandler((req, res) => {
    const body = v
      .object({ stars: v.int({ min: 1, max: 5 }), comment: v.text({ max: 400 }).optional() })
      .parse(req.body);
    const result = rateOrder({
      orderId: Number(req.params.id),
      user: req.user,
      stars: body.stars,
      comment: body.comment ?? '',
    });
    return created(res, result);
  }),
);

export default router;
